# Javascript Node 8 simple CircleCI 2.0 configuration file
# Eduardo San Martin Morote
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# Put this file in a .circleci/ folder
version: 2


jobs:
  deploy:
    machine: 
      enabled: true
    steps:
      - run:
          name: ssh
          command: ssh $SSH_USER@$SSH_HOST bash -c '
            pkill screen;
            pkill node;
            pkill nodemon;
            rm -rf Morph;
            git clone git@github.com:dukefromearth/Morph.git Morph;
            cd Morph/server;
            git checkout node-python-integration;
            git pull origin node-python-integration;
            npm i;
            screen -d -m npm start'
          

    #"pkill screen;rm -rf Morph;git clone git@github.com:dukefromearth/Morph.git Morph2;cd Morph2/server;npm i;npm start"
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
