export default class Shields {
    constructor(){
        this.shields = [
            [
            document.getElementById("l1_shield_f0"),
            document.getElementById("l1_shield_f1"),
            document.getElementById("l1_shield_f2"),
            document.getElementById("l1_shield_f3"),
            document.getElementById("l1_shield_f4"),
            document.getElementById("l1_shield_f5"),
            document.getElementById("l1_shield_f6"),
            document.getElementById("l1_shield_f7"),
            document.getElementById("l1_shield_f8"),
            document.getElementById("l1_shield_f9"),
            document.getElementById("l1_shield_f10"),
            document.getElementById("l1_shield_f11"),
            document.getElementById("l1_shield_f12"),
            document.getElementById("l1_shield_f13"),
            document.getElementById("l1_shield_f14"),
            document.getElementById("l1_shield_f15"),
            document.getElementById("l1_shield_f16"),
            document.getElementById("l1_shield_f17"),
            document.getElementById("l1_shield_f18"),
            document.getElementById("l1_shield_f19")
          ],
          [
            document.getElementById("l2_shield_f0"),
            document.getElementById("l2_shield_f1"),
            document.getElementById("l2_shield_f2"),
            document.getElementById("l2_shield_f3"),
            document.getElementById("l2_shield_f4"),
            document.getElementById("l2_shield_f5"),
            document.getElementById("l2_shield_f6"),
            document.getElementById("l2_shield_f7"),
            document.getElementById("l2_shield_f8"),
            document.getElementById("l2_shield_f9")
          ],
          [
            document.getElementById("l3_shield_f0"),
            document.getElementById("l3_shield_f1"),
            document.getElementById("l3_shield_f2"),
            document.getElementById("l3_shield_f3"),
            document.getElementById("l3_shield_f4"),
            document.getElementById("l3_shield_f5"),
            document.getElementById("l3_shield_f6"),
            document.getElementById("l3_shield_f7"),
            document.getElementById("l3_shield_f8"),
            document.getElementById("l3_shield_f9"),
            document.getElementById("l3_shield_f10")
          ]
        ]
        this.counter = [0,0,0];
    }
}